---

# - name: Refresh inventory
#   ansible.builtin.meta: refresh_inventory

- name: Get RHEL node
  set_fact:
    node_name: "{{ item }}"
  loop: "{{ groups['all'] }}"
  when: hostvars[item].tags is defined and hostvars[item].tags.Name | regex_search("^rhel-(.*)$")

- name: Add RHEL node to the rhel group
  add_host:
    name: "{{ node_name }}"
    groups: "rhel"
  when: node_name is defined
