---

- amazon.aws.ec2_vpc_subnet_info:
    filters:
      "tag:name": "{{ ec2_vpc_name }}"
  register: vpc
      
- name: Terminate RHEL instance
  amazon.aws.ec2_instance:
    state: absent
    region: "{{ ec2_vpc_region }}"
    filters:
      "tag:name": "{{ ec2_instance_name }}"

- name: Delete Security Group
  amazon.aws.ec2_group:
    name: "{{ ec2_sg_name }}"
    region: "{{ ec2_vpc_region }}"
    state: absent

- name: Delete Subnet in VPC
  amazon.aws.ec2_vpc_subnet:
    vpc_id: "{{ vpc.vpc.id }}"
    cidr: "{{ ec2_subnet_cidr }}"
    region: "{{ ec2_vpc_region }}"
    state: absent
    tags:
      name: "{{ ec2_subnet_name }}"

- name: Delete Route Table and add IGW route
  amazon.aws.ec2_vpc_route_table:
    vpc_id: "{{ vpc.vpc.id }}"
    region: "{{ ec2_vpc_region }}"
    state: absent
    tags:
      name: "{{ ec2_rt_name }}"
    subnets:
      - "{{ subnet.subnet.id }}"
    routes:
      - dest: 0.0.0.0/0
        gateway_id: "{{ igw.gateway_id }}"

- name: Delete Internet Gateway (IGW)
  amazon.aws.ec2_vpc_igw:
    vpc_id: "{{ vpc.vpc.id }}"
    region: "{{ ec2_vpc_region }}"
    state: absent
    tags:
      name: "{{ ec2_igw_name }}"

- name: Create VPC {{ ec2_vpc_name }}
  amazon.aws.ec2_vpc_net:
    name: "{{ ec2_vpc_name }}"
    cidr_block: "{{ ec2_vpc_cidr }}"
    region: "{{ ec2_vpc_region }}"
    state: absent

