---

- amazon.aws.ec2_vpc_net_info:
    region: "{{ ec2_vpc_region }}"
    filters:
      "tag:name": "{{ ec2_vpc_name }}"
  register: vpc
      
- name: Terminate RHEL instance
  amazon.aws.ec2_instance:
    state: absent
    region: "{{ ec2_vpc_region }}"
    filters:
      "tag:name": "{{ ec2_instance_name }}"

- name: Delete Security Group
  amazon.aws.ec2_group:
    name: "{{ ec2_sg_name }}"
    region: "{{ ec2_vpc_region }}"
    state: absent

- debug: 
    var: vpc

- debug: 
    var: vpc.vpcs[0]

- debug: 
    var: vpc.vpcs[0].vpc_id

- name: Delete Subnet in VPC
  amazon.aws.ec2_vpc_subnet:
    vpc_id: "{{ vpc.vpcs[0].id }}"
    cidr: "{{ ec2_subnet_cidr }}"
    region: "{{ ec2_vpc_region }}"
    state: absent
    filters:
      "tag:name": "{{ ec2_subnet_name }}"

- name: Delete Route Table and add IGW route
  amazon.aws.ec2_vpc_route_table:
    vpc_id: "{{ vpc.vpcs[0].id }}"
    region: "{{ ec2_vpc_region }}"
    state: absent
    filters:
      "tag:name": "{{ ec2_rt_name }}"

- name: Delete Internet Gateway (IGW)
  amazon.aws.ec2_vpc_igw:
    vpc_id: "{{ vpc.vpcs[0].id }}"
    region: "{{ ec2_vpc_region }}"
    state: absent
    filters:
      "tag:name": "{{ ec2_igw_name }}"

- name: Create VPC {{ ec2_vpc_name }}
  amazon.aws.ec2_vpc_net:
    name: "{{ ec2_vpc_name }}"
    vpc_id: "{{ vpc.vpcs[0].id }}"
    filters:
      "tag:name": "{{ ec2_vpc_name }}"
    state: absent

